export const languageData = {
  english: {
    login: {
      login: "login",
      username: "Username",
      usernamePlaceholder: "Enter Username",
      password: "Password",
      passwordPlaceholder: "Enter Password",
      forgetPassword: "forgetPassword",
      title: "Welcome Back !",
      subtitle: "Sign in to continue to VMC - Secretary Portal.",
      toastUsername: "Please Enter Username",
      toastPassword: "Please Enter Password",
    },
    header: {
      profile: "profile",
      logout: "logout",
    },
    noRecords: "No Records Found!!",
    role: {
      access: "Access",
      create: "Create",
      edit: "Edit",
      list: "List",
      role: "Role",
      addRole: "Add Role",
      master: "Master",
      dashboard: "Dashboard",
      isAdmin: "IsAdmin",
      permission: "Permission",
      employeeMaster: "Employee Master",
      userManagement: "User Management",
      administrative: "Administrative Work",
      letter: "Letter",
      salary: "Salary",
      member: "Member",
      memberDisciplinaryDetails: "Member Disciplinary Details",
      proposal: "Proposal",
      agenda: "Agenda",
      script: "Script",
      committee: "Committee",
      councilors: "Councilors",
      proposals: "Proposals",
      delete: "Delete",
      roleName: "Role Name",
      editRole: "Edit Role",
      roleList: "Role List",
      roleToastError: "Role Name is Required!",
      roleSearchPlaceholder: "Search for Role...",
    },
    employee: {
      addEmployee: "Add User",
      editEmployee: "Edit User",
      userName: "Username",
      userNamePlaceholder: "Enter Username",
      password: "Password",
      passwordPlaceholder: "Enter Password",
      role: "Role",
      rolePlaceholder: "Select Role",
      name: "Name",
      namePlaceholder: "Enter Name",
      email: "Email",
      emailPlaceholder: "Enter Email",
      mobileNo: "Mobile No",
      mobileNoPlaceholder: "Enter Mobile No",
      alternativeNo: "Alternative No",
      alternativeNoPlaceholder: "Enter Alternative No",
      address: "Address",
      addressPlaceholder: "Enter Address",
      employeeList: "User List",
      user: "User",
      employeeMaster: "Employee Master",
      employeeNameSearchPlaceholder: "Search for User Name...",
      employeeMobileSearchPlaceholder: "Search for User Mobile...",
      userNameToastError: "Please Enter a UserName",
      emailToastError: "Please Enter a Email",
      emailProperToastError: "Email is not in proper format",
      passwordToastError: "Please Enter a Password",
      roleToastError: "Please Select a Role",
      mobileNoToastError: "Please Enter a MobileNo",
      mobileNoProperToastError: "MobileNo is not in proper format",
      addressToastError: "Please Enter a Address",
    },
    common: {
      close: "Close",
      add: "Add",
      edit: "Edit",
      view: "View",
      delete: "Delete",
      submit: "Submit",
      update: "Update",
      next: "Next",
      councillor: "Councillor",
      back: "Back",
      ok: "Ok",
      clearFilter: "Clear",
      filter: "Filter",
      deactiveMember: "Are you sure you want to deactivate the member?",
      yes: "Yes",
      areYouSure: "Are you sure ?",
      deleteMsg: "You want to remove this record ?",
      deleteIt: "Yes, Delete It!",
      save: "Save",
      preview: "Preview",
      print: "Print",
      printPreview: "Print & Preview",
      mergePdf: "Merge Pdf",
    },
    committee: {
      committeeList: "Committee List",
      addCommittee: "Add Committee",
      editCommittee: "Edit Committee",
      committee: "Committee",
      committeeName: "Committee Name",
      committeePlaceholder: "Enter Committee Name",
      committeeToastError: "Please Enter Committee Name",
      committeeSearchPlaceholder: "Search for Committee...",
      mincommitteeToastError:
        "Minimum 3 Characters Is Required In Commmittee Name",
    },
    educationQualification: {
      educationQualificationList: "Education Qualification List",
      addEducationQualification: "Add Education Qualification",
      editEducationQualification: "Edit Education Qualification",
      educationQualification: "Education Qualification",
      educationQualificationName: "Qualification Name",
      educationQualificationPlaceholder: "Enter Qualification Name",
      educationQualificationToastError: "Please Enter Qualification Name",
      educationQualificationSearchPlaceholder: "Search for Qualification...",
      mineducationQualificationToastError:
        "Minimum 3 Characters Is Required In Education Qualification Name",
    },
    incumbencyDetails: {
      incumbencyDetailsList: "Incumbency Detail List",
      addIncumbencyDetails: "Add Incumbency Detail",
      editIncumbencyDetails: "Edit Incumbency Detail",
      incumbencyDetails: "Incumbency Detail",
      incumbencyDetailsName: "Incumbency Detail Name",
      incumbencyDetailsPlaceholder: "Enter Incumbency Detail Name",
      incumbencyDetailsToastError: "Please Enter Incumbency Detail Name",
      incumbencyDetailsSearchPlaceholder: "Search for Incumbency Detail...",
      minincumbencyDetailsToastError:
        "Minimum 3 Characters Is Required In Incumbency Detail Name",
    },
    designation: {
      designation: "Designation",
      addDesignation: "Add Designation",
      editDesignation: "Edit Designation",
      designationList: "Designation List",
      designationName: "Designation Name",
      designationPlaceholder: "Enter Designation Name",
      designationToastError: "Please Enter Designation Name",
      designationSearchPlaceholder: "Search for Desgination...",
      mindesignationToastError:
        "Minimum 3 Characters Is Required In Designation Name",
    },
    ward: {
      ward: "Ward",
      addWard: "Add Ward",
      editWard: "Edit Ward",
      wardList: "Ward List",
      wardName: "Ward Name",
      wardPlaceholder: "Enter Ward Name",
      wardToastError: "Please Enter Ward Name",
      wardSearchPlaceholder: "Search for Ward...",
      minwardToastError: "Minimum 3 Characters Is Required In Ward Name",
    },
    politicalParty: {
      politicalParty: "Political Party",
      addPoliticalParty: "Add Political Party",
      editPoliticalParty: "Edit Political Party",
      politicalPartyList: "Political Party List",
      politicalPartyName: "Political Party Name",
      politicalPartyPlaceholder: "Enter Political Party Name",
      politicalPartyToastError: "Please Enter Political Party Name",
      politicalPartySearchPlaceholder: "Search for Political Party...",
      minpoliticalpartyToastError:
        "Minimum 3 Characters Is Required In Political Party Name",
    },
    member: {
      memberProfile: "Member Profile",
      member: "Member",
      addMember: "Add Member",
      editMember: "Edit Member",
      memberList: "Member Profile List",
      memberName: "Member Name",
      memberPlaceholder: "Enter Member Name",
      memberToastError: "Please Enter Member Name",
      sameAsRa: "Same As a RA",
      personalDetails: "Personal Details",
      bankDetails: "Bank Details",
      electionWard: "Election Ward",
      termsDetails: "Terms Details",
      politicalParty: "Political Party",
      electedMemberName: "Elected Member Name",
      mobileNo: "Mobile No",
      residentialAddress: "Residential Address",
      communicationAddress: "Communication Address",
      pincode: "Pincode",
      bloodGroup: "Blood Group",
      gender: "Gender",
      birthDate: "Birth Date",
      whatsappNo: "Whatsapp No",
      residenceNo: "Residence No",
      officeNo: "Office No",
      email: "Email",
      educationQuality: "Education Quality",
      detailEducation: "Detail Education",
      otherQuality: "Other / Special Quality",
      signature: "Signature",
      bankName: "Bank Name",
      branchName: "Branch Name",
      accountNo: "Account No",
      accountType: "Account Type",
      ifscCode: "IFSC Code",
      panNo: "PAN No",
      remarks: "Remarks",
      caste: "Caste",
      electionWardPlaceholder: "Select Election Ward",
      politicalPartyPlaceholder: "Select Political Party",
      electedMemberNamePlaceholder: "Enter Elected Member Name",
      mobileNoPlaceholder: "Enter Mobile No",
      residentialAddressPlaceholder: "Enter Residential Address",
      communicationAddressPlaceholder: "Enter Communication Address",
      pincodePlaceholder: "Enter Pincode",
      bloodGroupPlaceholder: "Blood Group",
      GenderPlaceholder: "Select Gender",
      birthDatePlaceholder: "Enter Birth Date",
      whatsappNoPlaceholder: "Enter Whatsapp No",
      residenceNoPlaceholder: "Enter Residence No",
      officeNoPlaceholder: "Enter Office No",
      emailPlaceholder: "Enter Email",
      educationQualityPlaceholder: "Select Education Quality",
      detailEducationPlaceholder: "Enter Detail Education",
      otherQualityPlaceholder: "Enter Other Quality",
      signaturePlaceholder: "Enter Signature",
      bankNamePlaceholder: "Enter Bank Name",
      branchNamePlaceholder: "Enter Branch Name",
      accountNoPlaceholder: "Enter Account No",
      accountTypePlaceholder: "Select Account Type",
      ifscCodePlaceholder: "Enter IFSC Code",
      panNoPlaceholder: "Enter PAN No",
      electionWardToastError: "Please Select Election Ward",
      politicalPartyToastError: "Please Select Political Party",
      electedMemberNameToastError: "Please Enter Elected Member Name",
      mobileNoToastError: "Please Enter Mobile No",
      residentialAddressToastError: "Please Enter Residential Address",
      communicationAddressToastError: "Please Enter Communication Address",
      pincodeToastError: "Please Enter Pincode",
      pincodeInCorrectToastError: "Please Enter Pincode in Correct Format",
      bloodGroupToastError: "Please Enter Blood Group",
      genderToastError: "Please Enter Gender",
      birthDateToastError: "Please Enter Birth Date",
      casteToastError: "Please Enter Caste",
      whatsappNoToastError: "Please Enter Whatsapp No",
      whatsappNoIncorrectToastError:
        "Please Enter Whatsapp No in Correct Format",
      residenceNoToastError: "Please Enter Residence No",
      officeNoToastError: "Please Enter Office No",
      emailToastError: "Please Enter Email",
      emailIncorrectToastError: "Please Enter Email in Correct Format",
      educationQualityToastError: "Please Select Education Quality",
      detailEducationToastError: "Please Enter Detail Education",
      serialNo: "Serial No",
      year: "Year",
      serialNoPlaceholder: "Enter Serial No",
      yearPlaceholder: "Select Year",
      serialNoToastError: "Please Enter Serial No",
      yearToastError: "Please Select Year",
      otherQualityToastError: "Please Enter Other Quality",
      signatureToastError: "Please Enter Signature",
      bankNameToastError: "Please Enter Bank Name",
      branchNameToastError: "Please Enter Branch Name",
      accountNoToastError: "Please Enter Account No",
      accountTypeToastError: "Please Select Account Type",
      ifscCodeToastError: "Please Enter IFSC Code",
      ifscCodeIncorrectToastError: "Please Enter IFSC Code in Correct Format",
      panNoToastError: "Please Enter PAN No",
      panNoToastIncorrectError: "Please Enter PAN No in Correct Format",
      memberNameSearchPlaceholder: "Search for Member Name...",
      memberMobileSearchPlaceholder: "Search for Member Mobile...",
      activeSearchPlaceholder: "Search for Active Status...",
      memberWardSearchPlaceholder: "Search for Member Ward...",
      memberPoliticalPartySearchPlaceholder:
        "Search for Member Political Party...",
    },
    memberDisciplinary: {
      memberDisciplinaryDetails: "Member Disciplinary Details",
      memberDisciplinaryList: "Member Disciplinary List",
      addDisciplinaryDetails: "Add Disciplinary Details",
      editDisciplinaryDetails: "Edit Disciplinary Details",
      electedMember: "Elected Member",
      committee: "Committee",
      designation: "Designation",
      terms: "Term",
      fromDate: "Term Start Date",
      toDate: "Term End Date",
      activeDocument: "Active Document",
      inActiveDocument: "Inactive Document",
      incumbencyDetails: "Incumbency Details",
      incumbencyDetailsPlaceholder: "Select Incumbency Details",
      incumbencyDetailsToastError: "Please Select Incumbency Details",
      electedMemberPlaceholder: "Select Elected Member",
      committeePlaceholder: "Select Committee",
      designationPlaceholder: "Select Designation",
      memberToastError: "Please Select Member",
      committeeToastError: "Please Select Committee",
      designationToastError: "Please Select Designation",
      fromDateToastError: "Please Select Term Start Date",
      toDateToastError: "Please Select Term End Date",
      activeDocumentToastError: "Please Upload Active Document",
      inActiveDocumentToastError: "Please Upload Inactive Document",
    },
    proposalType: {
      proposalType: "Proposal Type",
      addProposalType: "Add Proposal Type",
      editProposalType: "Edit Proposal Type",
      proposalTypeList: "Proposal Type List",
      proposalTypeName: "Proposal Type Name",
      proposalTypePlaceholder: "Enter Proposal Type Name",
      proposalTypeToastError: "Please Enter Proposal Type Name",
      proposalTypeSearchPlaceholder: "Search for Proposal Type...",
      minproposalTypeToastError:
        "Minimum 3 Characters Is Required In Proposal Type",
    },
    proposalFor: {
      proposalFor: "Proposal For",
      addProposalFor: "Add Proposal For",
      editProposalFor: "Edit Proposal For",
      proposalForList: "Proposal For List",
      proposalForName: "Proposal For Name",
      proposalForPlaceholder: "Enter Proposal For Name",
      proposalForToastError: "Please Enter Proposal For Name",
      proposalForSearchPlaceholder: "Search for Proposal For...",
      minproposalForToastError:
        "Minimum 3 Characters Is Required In Proposal For",
    },
    status: {
      status: "Status",
      addStatus: "Add Status",
      editStatus: "Edit Status",
      statusList: "Status List",
      statusName: "Status Name",
      statusPlaceholder: "Enter Status Name",
      statusToastError: "Please Enter Status Name",
      statusSearchPlaceholder: "Search for Status...",
      minstatusToastError: "Minimum 3 Characters Is Required In Status",
    },
    year: {
      year: "Year",
      addYear: "Add Year",
      editYear: "Edit Year",
      yearList: "Year List",
      yearName: "Year",
      isActive: "IsActive",
      yearPlaceholder: "Enter Year",
      yearToastError: "Please Enter Year",
      yearSearchPlaceholder: "Search for Year...",
      minyearToastError: "Minimum 3 Characters Is Required In Year",
    },
    proposal: {
      proposal: "Proposal ",
      addProposal: "Add Proposal ",
      editProposal: "Edit Proposal ",
      proposalList: "Proposal List",
      proposalNo: "Proposal No",
      sankalanNo: "Sankalan No",
      mukSankalanNo: "Muk.Sankalan No",
      incomingDate: "Incoming Date",
      proposalDate: "Proposal Date",
      inwardDate: "Inward Date",
      inwardTime: "Inward Time",
      title: "Title",
      keywords: "Keywords",
      committee: "Committee",
      department: "Department",
      subject: "Subject",
      committeeInwardNo: "Committee Inward No",
      registerInwardNo: "Register Inward No",
      proposalType: "Proposal Type",
      proposalFor: "Proposal For",
      proposalForCommittee: "Proposal For ( Committee )",
      proposalStatus: "Proposal Status",
      uploadDocument: "Upload Document",
      sankalanNoPlaceholder: "Enter Sankalan No",
      mukSankalanNoPlaceholder: "Enter Muk. Sankalan No",
      incomingDatePlaceholder: "Enter Incoming Date",
      titlePlaceholder: " Enter Title",
      committeePlaceholder: " Select Committee",
      departmentPlaceholder: " Select Department",
      subjectPlaceholder: " Enter Subject",
      committeeInwardNoPlaceholder: " Enter Committee Inward No",
      registerInwardNoPlaceholder: " Enter Reg. Inward No",
      proposalTypePlaceholder: " Select Proposal Type",
      proposalForPlaceholder: " Select Proposal For",
      proposalForCommitteePlaceholder: " Select Proposal For ( Committee )",
      proposalStatusPlaceholder: " Select Proposal Status",
      sankalanNoToastError: "Please Enter sankalan No",
      mukSankalanNoToastError: "Please Enter Muk.sankalan No",
      incomingDateToastError: "Please Enter Proposal Date",
      inwardDateToastError: "Please Enter Reg. Inward Date",
      inwardTimeToastError: "Please Enter Reg. Inward Time",
      titleToastError: "Please Enter Title",
      keywordsToastError: "Please Enter Keywords",
      committeeToastError: "Please Select Committee",
      departmentToastError: "Please Select Department",
      subjectToastError: "Please Enter Subject",
      committeeInwardNoToastError: "Please Enter Committee Inward No",
      registerInwardNoToastError: "Please  Enter Register Inward No",
      proposalTypeToastError: "Please Select Proposal Type",
      proposalForToastError: "Please Select Proposal For",
      proposalStatusToastError: "Please Select Proposal Status",
      uploadDocumentToastError: "Please Upload Document",
      image: "Image",
      video: "Video",
      pdf: "Pdf",
      sankalanNoSearchPlaceholder: "Search for Sankalan No...",
      inwardNoSearchPlaceholder: "Search for Register Inward No...",
      fromDateSearchPlaceholder: "From Date",
      toDateSearchPlaceholder: "To Date",
      registerinwardTimePlaceholder: "Select Reg. Inward Time",
    },
    script: {
      script: "Script​",
      scriptNo: "Script No​",
      scriptlist: "Script List​",
      addScript: "Generate Script​",
      editScript: "Edit Script​",
      viewScript: "View Script​",
      proposalNo: "Proposal No",
      proposalNoPlaceholder: "Enter Proposal No",
      statusPlaceholder: "Select Status",
      proposalNoToast: "Please Enter Proposal No",
      date: "Date",
      datePlaceholder: "Enter Date",
      dateToast: "Please Enter Date",
      regInvertNo: "Reg. Invert No",
      regInwartNoPlaceholder: "Enter Reg. Invert No",
      regInwartNoToast: "Please Enter Reg. Invert No",
      ejardar: "Ejardar",
      ejardarPlaceholder: "Enter Ejardar Name",
      ejardarToast: "Please Enter Ejardar Name",
      scriptFieled: "Script",
      scriptFieledPlaceholder: "Enter Script",
      scriptFieledToast: "Please Enter Script",
      remarks: "Remarks",
      remarksPlaceholder: "Enter Remarks​",
      amount: "Amount",
      amountPlaceholder: "Enter Amount",
      amountToast: "Please Enter Amount",
    },
    agendaStatus: {
      agendaStatus: "Agenda Status",
      addAgendaStatus: "Add Agenda Status",
      editAgendaStatus: "Edit Agenda Status",
      agendaStatusList: "Agenda Status List",
      agendaStatusName: "Agenda Status Name",
      agendaStatusPlaceholder: "Enter Agenda Status Name",
      agendaStatusToastError: "Please Enter Agenda Status Name",
      agendaStatusSearchPlaceholder: "Search for Agenda Status...",
      minagendastatusToastError:
        "Minimum 3 Characters Is Required In Agenda Status",
    },
    agenda: {
      agenda: "Agenda",
      addAgenda: "Add Agenda",
      editAgenda: "Edit Agenda",
      agendaList: "Agenda List",
      agendaName: "Agenda Name",
      agendaDate: "Agenda Date",
      agendaCreatedDate: "Create Agenda Date",
      subjectModal: "Subject Details",
      subject: "Subject",

      mettingDate: "Agenda Meeting Date",
      time: "Agenda Time",
      proposalFor: "Proposal For",
      agendaDatePlaceholder: "Select Agenda Date",
      mettingDatePlaceholder: "Select Agenda Meeting Date",
      timePlaceholder: "Select Agenda Time",
      proposalForPlaceholder: "Select Proposal For",
      agendaDateToastError: "Please Select Agenda Date",
      mettingDateToastError: "Please Select Agenda Meeting Date",
      timeToastError: "Please Select Agenda Time",
      proposalForToastError: "Please Select Proposal For",
      agendaPlaceholder: "Enter Agenda Name",
      agendaToastError: "Please Enter Agenda Name",
      shortScript: "Short Script",
      srNo: "Sr. No.",
      committee: "Committee",
      script: "Script",
      status: "Status",
      remarks: "Remarks",
      addRemarks: "Add Remarks",
      remarksToastError: "Please Enter a Remarks",
      date: "Date",
      addShortScript: "Add Short Script",
      agendaNo: "Agenda No",
      agendaTitle: "Agenda Title",
      day: "Day",
      purvani: "Purvani",
      addPurvani: "Add Purvani",
      purvaniAgendaToast: "Please Select a Script",
      sendForApproval: "Send For Approval",
      approvalMsg: "Are you sure you want to Add this Purvani To Agenda No ",
      fromPersonName: "From Person Name",
      letterHead: "LetterHead Paper",
      plainPaper: "Plain Paper",
      postName: "Post Name",
    },
    languageType: {
      languageTypeList: "Language Type List",
      addLanguageType: "Add Language Type",
      editLanguageType: "Edit Language Type",
      languageType: "Language Type",
      languageName: "Language Name",
      languagePlaceholder: "Enter Language Name",
      languageToastError: "Please Enter Language Name",
      languageCode: "Language Code",
      languageCodePlaceholder: "Enter Language Code",
      languageCodeToastError: "Please Enter Language Code",
      languageTypeSearchPlaceholder: "Search for Language Type...",
      minlanguageTypeToastError:
        "Minimum 3 Characters Is Required In Language Type",
      minlanguageCodeToastError:
        "Minimum 2 Characters Is Required In Language Code",
    },
    letterType: {
      letterTypeList: "Letter Type List",
      addLetterType: "Add Letter Type",
      editLetterType: "Edit Letter Type",
      letterType: "Letter Type",
      letterName: "Letter Name",
      letterPlaceholder: "Enter Letter Name",
      letterToastError: "Please Enter Letter Name",
      letterTypeSearchPlaceholder: "Search for Letter Type...",
      minletterTypeToastError:
        "Minimum 3 Characters Is Required In Letter Type",
      letterForToastError: "Please Select Letter For",
      letterForPlaceHolder: "Select Letter For",
      letterTypePlaceHolder: "Select Letter Type",
    },
    letterField: {
      letterFieldList: "Letter Field List",
      addLetterField: "Add Letter Field",
      editLetterField: "Edit Letter Field",
      letterField: "Letter Field",
      fieldName: "Field Name",
      fieldPlaceholder: "Enter Field Name",
      fieldToastError: "Please Enter Field Name",
      letterToastError: "Please Select Letter Type",
      dataTypeToastError: "Please Enter Field Data Type Name",
      fieldTokenToastError: "Please Enter Field Token Name",
      letterType: "Letter Type",
      letterTypePlaceHolder: "Select Letter Type",
      fieldType: "Field Type",
      fieldToken: "Field Token",
      fieldDataTypePlaceholder: "Select Field Data Type",
      fieldTokenPlaceholder: "Enter Field Token",
      letterFieldSearchPlaceholder: "Search for Letter Field...",
      letterTypeSearchPlaceholder: "Search for Letter Type...",
      letterTokenPlaceholder: "Select Field Name",
    },
    letterContent: {
      letterContentList: "Letter Content List",
      addLetterContent: "Add Letter Content",
      editLetterContent: "Edit Letter Content",
      letterContent: "Letter Content",
      content: "Content",
      contentPlaceholder: "Enter Content",
      contentToastError: "Please Enter Content",
      languageType: "Language Type",
      languagePlaceholder: "Select Language Type",
      languageToastError: "Please Select Language Type",
      letterType: "Letter Type",
      letterTypePlaceholder: "Select Letter Type",
      letterTypeToastError: "Please Select Letter Type",
      letterTypeSearchPlaceholder: "Search for Letter Type...",
      minletterContentToastError:
        "Minimum 3 Characters Is Required In Letter Content",
    },
    changePassword: {
      changePassword: "Change Password",
      oldPassword: "Old Password",
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
      oldPasswordPlaceholder: "Enter Old Password",
      newPasswordPlaceholder: "Enter New Password",
      confirmPasswordPlaceholder: "Enter Confirm Password",
      oldPasswordToastError: "Please Enter Old Password",
      newPasswordToastError: "Please Enter New Password",
      confirmPasswordToastError: "Please Enter Confirm Password",
      oldPasswordToastError2: "Old Password is minimum length must be 6",
      newPasswordToastError2: "New Password is minimum length must be 6",
      passwordRegexToastError: "Password is not in proper format",
      confirmPasswordToastError2:
        "Confirm Password is minimum length must be 6",
      passwordNotMatchToastError:
        "New Password and Confirm Password does not match",
    },
    department: {
      department: "Department",
      addDepartment: "Add Department",
      editDepartment: "Edit Department",
      departmentList: "Department List",
      departmentName: "Department Name",
      departmentPlaceholder: "Enter Department Name",
      departmentToastError: "Please Enter Department Name",
      departmentSearchPlaceholder: "Search For Department...",
      mindepartmentToastError:
        "Minimum 3 Characters Is Required In Department Name",
    },
    letterFor: {
      letterFor: "Letter For",
      addletterFor: "Add Letter For",
      editletterFor: "Edit Letter For",
      letterForList: "Letter For List",
      letterForName: "Letter For Name",
      letterForPlaceholder: "Enter Letter For Name",
      letterForToastError: "Please Enter Letter For Name",
      letterForSearchPlaceholder: "Search for Letter For...",
      minletterForToastError: "Minimum 3 Characters Is Required In Letter For",
    },
    issueLetter: {
      issueLetter: "Issue Letter",
      addLetterHistory: "Add Issue Letter",
      letterHistory: "Issue Letter",
      letterHistoryList: "Issue Letter List",
      parameters: "Parameters",
      createdAt: "Created At",
      date: "Select Date",
    },
    pendingAgendaApproval: {
      pendingAgendaApproval: "Pending Agenda Approval",
      pendingAgendaApprovalList: "Pending Agenda Approval List",
      viewAgenda: "View Agenda",
      approveAgenda: "Approve",
      rejectAgenda: "Reject",
      approvalMsg: "Are you sure you want to Approve this record ?",
      rejectMsg: "Are you sure you want to Reject this record ?",
    },
    resolution: {
      resolution: "Resolution",
      resolutionList: "Resolution List",
      addresolution: "Add Resolution",
      postponed: "POSTPONED",
      adhyaksh: "Adhyaksh",
      nameProposal: "Proposers",
      nameApproval: "Approval",
      supporter: "Supporter",
      opposition: "Opposition",
      meaning: "Meaning",
      previousResolution: "Previous Resolution",
      nextResolution: "Next Resolution",
      remarks: "Remarks",
      adhyakshMemberToastError: "Please Select Adhyaksh",
      proposalOrCorrectionDetails: "Proposal / Improvement",
      confrimMsg: "Are you sure you want to Posponed Script ",
      contentTextSize: "Content Text Size",
      headerTextSize: "Header Text Size",
      notes: "Notes",
      showNameInPdf:
        "Are you want to show Supporter & Opposition Name in Pdf ?",
      addCorrectionProposal: "Add correction Proposal",
      deleteProposal: "Delete Proposal",
      correctionProposal: "Correction Proposal",
      correctionProposalToastError: "Please Enter a Correction Proposal",
    },
    proceeding: {
      proceeding: "Proceeding",
      addProceeding: "Add Proceeding",
      proceedingList: "Proceeding List",
      aboutMetting: "About Meeting",
      administrativeDetails: "Administrative Details",
      agendaToastError: "Please Select a Agenda",
      membersToastError: "Please Select a Members",
      aboutMettingToastError: "Please Enter About Meeting",
      administrativeDetailsToastError: "Please Enter Administrative Details",
      scriptNo: "Script No",
      scriptToastError: "Please Select Script",
    },
    stationeryMaterial: {
      stationeryMaterial: "Stationery Material",
      addStationeryMaterial: "Add Stationery Material",
      editStationeryMaterial: "Edit Stationery Material",
      stationeryMaterialList: "Stationery Material List",
      stationeryMaterialName: "Stationery Material Name",
      materialShortName: "Material Short Name",
      stationeryMaterialPlaceholder: "Enter Stationery Material Name",
      materialShortNamePlaceholder: "Enter Material Short Name",
      stationeryMaterialToastError: "Please Enter Stationery Material Name",
      materialShortNameToastError: "Please Enter Material Short Name",
      stationeryMaterialSearchPlaceholder: "Search for Stationery Material...",
      minstationeryMaterialToastError:
        "Minimum 3 Characters Is Required In Stationery Material",
      minmaterialShortNameToastError:
        "Minimum 3 Characters Is Required In Material Short Name",
    },
    stationeryWork: {
      stationeryWork: "Stationery Work",
      addStationeryWork: "Add Stationery Work",
      editStationeryWork: "Edit Stationery Work",
      stationeryWorkList: "Stationery Work List",
      stationeryWorkName: "Stationery Work Name",
      stationeryWorkPlaceholder: "Enter Stationery Work Name",
      stationeryWorkToastError: "Please Enter Stationery Work Name",
      stationeryWorkSearchPlaceholder: "Search for Stationery Work...",
      minstationeryWorkToastError:
        "Minimum 3 Characters Is Required In Stationery Work",
      date: "Date",
      date2: "Date2",
      datePlaceholder: "Select Date",
      date2Placeholder: "Select Date2",
      memberName: "Member Name",
      materialName: "Material Name",
      materialLanguage: "Material Langauage",
      qty: "Qty",
      issueMaterial: "Issue Material Details",
      supplyQty: "Supply Qty",
      price: "Price",
      remarks: "Remarks",
      memberPlaceholder: "Select Member Name",
      materialLanguagePlaceholder: "Material Language",
      dateToastError: "Please Select Date",
      memberNameToastError: "Please Select Member Name",
      materialLanguageToastError: "Please Select Material Language",
      materialNameToastError: "Please Select Material Name",
      qtyToastError: "Please Enter Qty",
      supplyQtyToastError: "Please Enter Supply Qty",
      priceToastError: "Please Enter Price",
      totalPrice: "Total Price",
      pageNo: "Page No",
      indexNo: "Index No",
      pageNoToastError: "Please Enter Page No",
      indexNoToastError: "Please Enter Index No",
    },
    salaryDetail: {
      salaryDetail: "Salary Detail ",
      addSalaryDetail: "Add Salary Detail ",
      editSalaryDetail: "Edit Salary Detail ",
      salaryDetailList: "Salary Detail List",
      houseBuildingLetterNo: "House Building Department letter",
      houseBuildingDate: "House Building Department Date",
      assemblyResolutionNo: "General Assembly Resolution No",
      assemblyResolutionDate: "General Assembly Resolution Date",
      declarationDate: "Declaration Date",
      totalSalary: "Total Salary",
      telephoneAllowance: "Telephone Allowance",
      stationeryAllowance: "Stationery Allowance",
      meetingAllowance: "Meeting Allowance",
      maximumMeetingAllowance: "Maximum Meeting Allowance",
      houseBuildingLetterNoToastError:
        "Please Enter House Building Department letter",
      houseBuildingDateToastError:
        "Please Enter House Building Department Date",
      assemblyResolutionNoToastError:
        "Please Enter General Assembly Resolution No",
      assemblyResolutionDateToastError:
        "Please Enter General Assembly Resolution Date",
      declarationDateToastError: "Please Enter Declaration Date",
      totalSalaryToastError: "Please Enter Total Salary",
      telephoneAllowanceToastError: "Please Enter Telephone Allowance",
      stationeryAllowanceToastError: "Please Enter Stationery Allowance",
      meetingAllowanceToastError: "Please Enter Meeting Allowance",
      maximumMeetingAllowanceToastError:
        "Please Enter Maximum Meeting Allowance",
    },
    issueSalary: {
      issueSalary: "Issue Salary",
      addIssueSalary: "Add Issue Salary",
      memberShipPageNo: "Membership Page No",
      totalDays: "Total Days",
      totalPrice: "Total Price",
      fromDateToastError: "Please Select From Date",
      toDateToastError: "Please Select To Date",
      memberShipPageNoToastError: "Please Enter a Membership page No",
    },
    vendorDetail: {
      vendorDetail: "Vendor Detail",
      addVendorDetail: "Add Vendor Detail",
      editVendorDetail: "Edit Vendor Detail",
      vendorDetailList: "Vendor Detail List",
      vendorName: "Vendor Name",
      companyName: "Company Name",
      address: "Address",
      mobileNo: "Mobile No",
      vendorNamePlaceholder: "Enter Vendor Name",
      vendorNameSearchPlaceholder: "Search Vendor Name",
      companyNamePlaceholder: "Enter Company Name",
      mobileNoPlaceholder: "Enter Mobile No",
      addressPlaceholder: "Enter Address",
      vendorNameToastError: "Please Enter Vendor Name",
      companyNameToastError: "Please Enter Company Name",
      mobileNoToastError: "Please Enter Mobile No",
      mobileNoLengthToastError: "Please Enter Proper Mobile No",
      addressToastError: "Please Enter Address",
      minLengthToastError: "Minimum 3 Characters Is Required",
    },
    paperDetail: {
      paperDetail: "Paper Detail",
      addPaperDetail: "Add Paper Detail",
      editPaperDetail: "Edit Paper Detail",
      paperDetailSerachPlaceholder: "Search Paper Name",

      paperDetailList: "Paper Detail List",
      paperName: "Paper Name",
      price: "Price",
      paperNamePlaceholder: "Enter Paper Name",
      pricePlaceholder: "Enter Price",
      paperNameToastError: "Please Enter Paper Name",
      priceToastError: "Please Enter Price",
      minLengthToastError: "Minimum 3 Characters Is Required",
    },
    paperWork: {
      paperWork: "Paper Work",
      addPaperWork: "Add Paper Work",
      editPaperWork: "Edit Paper Work",
      paperWorkList: "Paper Work List",
      month: "Month",
      advanceAmount: "Advance Amount",
      vendorPlaceholder: "Select Vendor Detail",
      monthPlaceholder: "Select Month",
      advanceAmountPlaceholder: "Enter a Advance Amount",
      vendorToastError: "Please Select Vendor Detail",
      monthToastError: "Please Select Month",
      advanceAmountToastError: "Please Enter Advance Amount",
      paperName: "Paper Name",
      paperType: "Paper Type",
      paperNamePlaceholder: "Select Paper Name",
      paperTypePlaceholder: "Select Paper Type",
      paperNameToastError: "Please Select Paper Name",
      paperTypeToastError: "Please Select Paper Type",
      day: "Day",
      price: "Price",
      totalPrice: "Total Price",
      qty: "Qty",
      amount: "Amount",
      dayToastError: "Please Enter Day",
      priceToastError: "Please Enter Price",
      totalPriceToastError: "Please Enter Total Price",
      qtyToastError: "Please Enter Qty",
      amountToastError: "Please Enter Amount",
    },
    dashboard: {
      totalScript: "Total Script",
      scriptStatus: "Script Status",
      upcomingMetting: "Upcoming Meeting",
      viewAll: "View All",
      proposalStatistics: "Proposal Statistics",
      totalProposal: "Total Proposal",
      totalGeneratedScript: "Total Generated Script",
      pendingGeneratedScript: "Pending Generated Script",
      issueLetterMsg:
        "The purpose of an issue letter is to formally communicate to the relevant parties.",
      totalissuedLetter: "Total Issued Letter",
      todayCount: "Toady's Count",
    },
    report: {
      report: "Report",
      reportType: "Report Type",
    },
    correctionProposal: {
      correctionProposalList: "Correction Proposal List",
      addCorrectionProposal: "Add Correction Proposal",
      editCorrectionProposal: "Edit Correction Proposal",
      correctionProposal: "Correction Proposal",
      correctionProposalSearchPlaceholder: "Search for Correction Proposal...",
      uploadData: "Upload Data",
      scriptToastError: "Script is Required",
      budgetItemSerialNo: "Budget Item Serial No",
      correctionProposalNo: "Correction Proposal No",
      arrangeCorrectionProposal: "Arrange Correction Proposal",
    },
  },
  gujarati: {
    login: {
      login: "પ્રવેશ કરો",
      username: "વપરાશકર્તાનું નામ",
      usernamePlaceholder: "વપરાશકર્તાનું નામ દાખલ કરો",
      password: "પાસવર્ડ",
      passwordPlaceholder: "પાસવર્ડ દાખલ કરો",
      forgetPassword: "પાસવર્ડ બદલો",
      title: "આપણું સ્વાગત છે!",
      subtitle: "VMC - સેક્રેટરી પોર્ટલમાં જોડાવા માટે દાખલ​ થાઓ.",
      toastUsername: "કૃપા કરીને વપરાશકર્તાનું નામ દાખલ કરો",
      toastPassword: "કૃપા કરીને પાસ​વર્ડ દાખલ કરો",
    },
    header: {
      profile: "પ્રોફાઇલ",
      logout: "લોગ આઉટ",
    },
    noRecords: "કોઈ રેકોર્ડ મળ્યો નથી!!",

    role: {
      access: "અધિકૃત",
      create: "ઉમેરો",
      edit: "સુધારો",
      master: "માસ્ટર",
      dashboard: "ડેશબોર્ડ",
      list: "દ્રશ્ય",
      role: "ભૂમિકા",
      addRole: "ભૂમિકા દાખલ કરો",
      isAdmin: "એડમિન છે?",
      permission: "પરવાનગી",
      employeeMaster: "વપરાશકર્તા",
      committee: "સમિતિ",
      councilors: "સભાસદશ્રીઓ",
      member: "સભ્ય",
      userManagement: "વપરાશકર્તા વ્યવસ્થાપન",
      administrative: "વહીવટી કાર્ય",
      letter: "પત્ર",
      salary: "માનદ વેતન",
      memberDisciplinaryDetails: "સભ્યની શાખાકીય બાબતો",
      proposal: "દરખાસ્તો",
      agenda: "એજન્ડા",
      script: "સંક્ષિપ્ત વર્ણન",
      proposals: "દરખાસ્તો",
      editRole: "ભૂમિકા સુધારો",
      delete: "કાઢી નાખો",
      roleName: "ભૂમિકાનું નામ",
      roleList: "ભૂમિકા દ્રશ્ય",
      roleToastError: "કૃપા કરીને ભૂમિકાનું નામ દાખલ કરો",
      roleSearchPlaceholder: "ભૂમિકા માટે શોધો...",
    },
    employee: {
      addEmployee: "વપરાશકર્તા ઉમેરો",
      editEmployee: "વપરાશકર્તામા સુધારો કરો",
      userName: "વપરાશી નામ (User Name)",
      userNamePlaceholder: "વપરાશકર્તાનું નામ દાખલ કરો",
      password: "પાસવર્ડ (Password)",
      passwordPlaceholder: "પાસવર્ડ દાખલ કરો",
      role: "જવાબદારી",
      rolePlaceholder: "જવાબદારી પસંદ કરો",
      name: "વપરાશકર્તાનું નામ",
      namePlaceholder: "નામ દાખલ કરો",
      email: "ઈ - મેઇલ",
      emailPlaceholder: "ઈ - મેઇલ દાખલ કરો",
      mobileNo: "મોબાઈલ નં",
      mobileNoPlaceholder: "મોબાઈલ નં. દાખલ કરો",
      alternativeNo: "અન્ય મોબાઈલ નં",
      alternativeNoPlaceholder: "અન્ય મોબાઈલ નં. દાખલ કરો",
      address: "સરનામું",
      addressPlaceholder: "સરનામું દાખલ કરો",
      employeeList: "વપરાશકર્તાની યાદી",
      employeeMaster: "વપરાશકર્તા",
      user: "વપરાશકર્તા",
      employeeNameSearchPlaceholder: "વપરાશકર્તાના નામ માટે શોધો......",
      employeeMobileSearchPlaceholder: "વપરાશકર્તાના મોબાઈલ માટે શોધો......",
      userNameToastError: "કૃપા કરીને વપરાશકર્તાનામ દાખલ કરો",
      emailToastError: "કૃપા કરીને ઇમેઇલ દાખલ કરો",
      emailProperToastError: "ઈમેલ યોગ્ય ફોર્મેટમાં નથી",
      passwordToastError: "કૃપા કરીને પાસવર્ડ દાખલ કરો",
      roleToastError: "કૃપા કરીને એક ભૂમિકા પસંદ કરો",
      mobileNoToastError: "કૃપા કરીને મોબાઇલ નંબર દાખલ કરો",
      mobileNoProperToastError: "મોબાઈલ નંબર યોગ્ય ફોર્મેટમાં નથી",
      addressToastError: "કૃપા કરીને સરનામું દાખલ કરો",
    },
    common: {
      submit: "દાખલ કરો ",
      update: "સુધારો કરો",
      councillor: "કાઉન્સિલર",
      add: "ઉમેરો",
      edit: "સુધારો",
      delete: "ડેલેટે",
      view: "જુઓ",

      close: "બંધ",
      next: "આગળ",
      back: "પાછળ",
      ok: "બરાબર",
      clearFilter: "ફિલ્ટર રદ કરો",
      filter: "ફિલ્ટર",
      deactiveMember: "શું તમે ખરેખર સભ્યને નિષ્ક્રિય કરવા માંગો છો?",
      yes: "હા",
      areYouSure: "શું તમને ખાતરી છે?",
      deleteMsg: "શું તમે ખરેખર આ રેકોર્ડ દૂર કરવા માંગો છો?",
      deleteIt: "હા, કાઢી નાખો!",
      save: "ઉમેરો",
      preview: "પૂર્વદર્શન",
      print: "છાપો",
      printPreview: "છાપો & પૂર્વદર્શન",
      mergePdf: "પીડીએફ મર્જ કરો",
    },
    committee: {
      committeeList: "સમિતિની યાદી",
      addCommittee: "સમિતિ દાખલ કરો ",
      editCommittee: "સમિતિમા સુધારો કરો",
      committee: "સમિતિ",
      committeeName: "સમિતિનું નામ",
      committeePlaceholder: "સમિતિનું નામ દાખલ કરો",
      committeeToastError: "કૃપા કરીને સમિતિનું નામ દાખલ કરો",
      committeeSearchPlaceholder: "સમિતિ માટે શોધો...",
      mincommitteeToastError: "સમિતિના નામમાં ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    educationQualification: {
      educationQualificationList: "શૈક્ષણિક લાયકાત યાદી",
      addEducationQualification: "શૈક્ષણિક લાયકાત ઉમેરો",
      editEducationQualification: "શૈક્ષણિક લાયકાતમાં સુધારો કરો",
      educationQualification: "શૈક્ષણિક લાયકાત",
      educationQualificationName: "લાયકાતનું નામ",
      educationQualificationPlaceholder: "લાયકાતનું નામ દાખલ કરો",
      educationQualificationToastError: "કૃપા કરીને લાયકાતનું નામ દાખલ કરો",
      educationQualificationSearchPlaceholder: "લાયકાત માટે શોધો...",
      mineducationQualificationToastError:
        "શૈક્ષણિક લાયકાતના નામમાં ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    incumbencyDetails: {
      incumbencyDetailsList: "સત્તાની વિગતોની યાદી",
      addIncumbencyDetails: "સત્તાની વિગતો દાખલ કરો ",
      editIncumbencyDetails: "સત્તાની વિગતોમા સુધારો કરો",
      incumbencyDetails: "સત્તાની વિગતો",
      incumbencyDetailsName: "સત્તાની વિગતોના નામ",
      incumbencyDetailsPlaceholder: "સત્તાની વિગતોના નામ દાખલ કરો",
      incumbencyDetailsToastError: "કૃપા કરીને સત્તાની વિગતોના નામ દાખલ કરો",
      incumbencyDetailsSearchPlaceholder: "સત્તાની વિગતો માટે શોધો...",
      minincumbencyDetailsToastError:
        "સત્તાની વિગતોમાં ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    designation: {
      designation: "જ​વાબદારી",
      addDesignation: "જ​વાબદારી દાખલ કરો",
      editDesignation: "જ​વાબદારી સુધારો",
      designationList: "જ​વાબદારીની યાદી",
      designationName: "જ​વાબદારીનું નામ",
      designationPlaceholder: "જ​વાબદારીનું નામ દાખલ કરો",
      designationToastError: "કૃપા કરીને જ​વાબદારીનું નામ દાખલ કરો",
      designationSearchPlaceholder: "જ​વાબદારી માટે શોધો...",
      mindesignationToastError: "જ​વાબદારીમાં ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    ward: {
      ward: "વોર્ડ",
      addWard: "વોર્ડ દાખલ કરો",
      editWard: "વોર્ડ સુધારો કરો",
      wardList: "વોર્ડની યાદી",
      wardName: "વોર્ડનું નામ ",
      wardPlaceholder: "વોર્ડનું નામ દાખલ કરો",
      wardToastError: "કૃપા કરીને વોર્ડનું નામ દાખલ કરો",
      wardSearchPlaceholder: "વોર્ડ માટે શોધો...",
      minwardToastError: "વોર્ડ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    politicalParty: {
      politicalParty: "રાજકીય પક્ષ",
      addPoliticalParty: "રાજકીય પક્ષ દાખલ કરો",
      editPoliticalParty: "રાજકીય પક્ષ સુધારો",
      politicalPartyList: "રાજકીય પક્ષની યાદી",
      politicalPartyName: "રાજકીય પક્ષનું નામ ",
      politicalPartyPlaceholder: "રાજકીય પક્ષનું નામ દાખલ કરો",
      politicalPartyToastError: "કૃપા કરીને રાજકીય પક્ષનું નામ દાખલ કરો",
      politicalPartySearchPlaceholder: "રાજકીય પક્ષ માટે શોધો...",
      minpoliticalpartyToastError:
        "રાજકીય પક્ષ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    member: {
      memberProfile: "સભ્ય પ્રોફાઇલ",
      member: "સભ્ય",
      addMember: "સભ્ય દાખલ કરો",
      editMember: "સભ્ય સુધારો",
      memberList: "સભ્ય પ્રોફાઇલની યાદી",
      memberName: "સભ્યનું નામ",
      memberPlaceholder: "સભ્યનું નામ દાખલ કરો",
      memberToastError: "કૃપા કરીને સભ્યનું નામ દાખલ કરો",
      personalDetails: "વ્યક્તિગત વિગતો",
      bankDetails: "બેંકની વિગતો",
      sameAsRa: "આરએ તરીકે સમાન",
      electionWard: "ચૂંટણી વોર્ડ",
      termsDetails: "ટર્મ​ની મુદત",
      politicalParty: "રાજકીય પક્ષ",
      electedMemberName: "ચૂંટાયેલા સભ્યનું નામ",
      mobileNo: "મોબાઇલ નંબર",
      residentialAddress: "રહેઠાણનું સરનામું",
      communicationAddress: "પત્ર​વ્ય​વહારનું સરનામું",
      pincode: "પીન કોડ",
      bloodGroup: "બ્લડ ગ્રુપ",
      gender: "લિંગ",
      birthDate: "જન્મતારીખ",
      whatsappNo: "વોટ્સએપ નંબર",
      detailEducation: "વિગતવાર શિક્ષણ",
      detailEducationPlaceholder: "વિગતવાર શિક્ષણ દાખલ કરો",
      detailEducationToastError: "કૃપા કરીને વિગતવાર શિક્ષણ દાખલ કરો",
      serialNo: "અનુક્રમ નંબર",
      year: "વર્ષ",
      serialNoPlaceholder: "અનુક્રમ નંબર દાખલ કરો",
      yearPlaceholder: "વર્ષ પસંદ કરો",
      serialNoToastError: "કૃપા કરીને અનુક્રમ નંબર દાખલ કરો",
      yearToastError: "કૃપા કરીને વર્ષ પસંદ કરો",
      residenceNo: "રહેઠાણ નંબર",
      officeNo: "ઓફિસ નંબર",
      email: "ઈ - મેઇલ",
      educationQuality: "શિક્ષણની ગુણવત્તા",
      otherQuality: "અન્ય ગુણવત્તા",
      signature: "સહી",
      bankName: "બેંકનું નામ",
      branchName: "શાખાનું નામ",
      accountNo: "ખાતા નંબર",
      accountType: "ખાતાનો પ્રકાર",
      ifscCode: "IFSC કોડ",
      panNo: "પાન નંબર",
      remarks: "વિશેષ નોંધ",
      electionWardPlaceholder: "ચૂંટણી વોર્ડ પસંદ કરો",
      politicalPartyPlaceholder: "રાજકીય પક્ષ પસંદ કરો",
      electedMemberNamePlaceholder: "ચૂંટાયેલા સભ્યનું નામ દાખલ કરો",
      mobileNoPlaceholder: "મોબાઇલ નંબર  દાખલ કરો",
      residentialAddressPlaceholder: "રહેઠાણનું સરનામું  દાખલ કરો",
      communicationAddressPlaceholder: "પત્ર​વ્ય​વહારનું સરનામું  દાખલ કરો",
      pincodePlaceholder: "પીન કોડ  દાખલ કરો",
      bloodGroupPlaceholder: "બ્લડ ગ્રુપ  દાખલ કરો",
      genderPlaceholder: "લિંગ દાખલ કરો",
      birthDatePlaceholder: "જન્મતારીખ  દાખલ કરો",
      caste: "જાતિ",
      casteToastError: "કૃપા કરીને જાતિ દાખલ કરો",
      whatsappNoPlaceholder: "વોટ્સએપ નંબર દાખલ કરો",
      residenceNoPlaceholder: "રહેઠાણ નંબર દાખલ કરો",
      officeNoPlaceholder: "ઓફિસ નંબર દાખલ કરો",
      emailPlaceholder: "ઈ - મેઇલનું  દાખલ કરો",
      educationQualityPlaceholder: "શિક્ષણની ગુણવત્તા દાખલ કરો",
      otherQualityPlaceholder: "અન્ય ગુણવત્તા દાખલ કરો",
      signaturePlaceholder: "સહી દાખલ કરો",
      bankNamePlaceholder: "બેંકનું નામ દાખલ કરો",
      branchNamePlaceholder: "શાખાનું નામ  દાખલ કરો",
      accountNoPlaceholder: "ખાતા નંબર  દાખલ કરો",
      accountTypePlaceholder: "ખાતાનો પ્રકાર દાખલ કરો",
      ifscCodePlaceholder: "IFSC કોડ  દાખલ કરો",
      panNoPlaceholder: "પાન નંબર દાખલ કરો",
      electionWardToastError: "કૃપા કરીને  ચૂંટણી વોર્ડ પસંદ કરો",
      politicalPartyToastError: "કૃપા કરીને  રાજકીય પક્ષ પસંદ કરો",
      electedMemberNameToastError: "કૃપા કરીને  ચૂંટાયેલા સભ્યનું  દાખલ કરો",
      mobileNoToastError: "કૃપા કરીને  મોબાઇલ નંબર દાખલ કરો",
      residentialAddressToastError: "કૃપા કરીને  રહેઠાણનું સરનામું દાખલ કરો",
      communicationAddressToastError:
        "કૃપા કરીને  પત્ર​વ્ય​વહારનું સરનામું દાખલ કરો",
      pincodeToastError: "કૃપા કરીને  પીન કોડ દાખલ કરો",
      pincodeInCorrectToastError: "કૃપા કરીને સાચા ફોર્મેટમાં પિનકોડ દાખલ કરો",
      bloodGroupToastError: "કૃપા કરીને  બ્લડ ગ્રુપ  દાખલ કરો",
      genderToastError: "કૃપા કરીને લિંગ દાખલ કરો",
      birthDateToastError: "કૃપા કરીને  જન્મતારીખ  દાખલ કરો",
      whatsappNoToastError: "કૃપા કરીને  વોટ્સએપ નંબર  દાખલ કરો",
      whatsappNoIncorrectToastError:
        "કૃપા કરીને સાચા ફોર્મેટમાં વોટ્સએપ નંબર દાખલ કરો",
      residenceNoToastError: "કૃપા કરીને  રહેઠાણ નંબર  દાખલ કરો",
      officeNoToastError: "કૃપા કરીને  ઓફિસ નંબર  દાખલ કરો",
      emailToastError: "કૃપા કરીને  ઈ - મેઇલનું  દાખલ કરો",
      emailIncorrectToastError: "કૃપા કરીને સાચા ફોર્મેટમાં ઈ - મેઇલ દાખલ કરો",
      educationQualityToastError: "કૃપા કરીને  શિક્ષણની ગુણવત્તા દાખલ કરો",
      otherQualityToastError: "કૃપા કરીને  અન્ય ગુણવત્તા  દાખલ કરો",
      signatureToastError: "કૃપા કરીને સહી દાખલ કરો",
      bankNameToastError: "કૃપા કરીને બેંકનું નામ દાખલ કરો",
      branchNameToastError: "કૃપા કરીને શાખાનું નામ દાખલ કરો",
      accountNoToastError: "કૃપા કરીને ખાતાનો નંબર દાખલ કરો",
      accountTypeToastError: "કૃપા કરીને ખાતાનો પ્રકાર દાખલ કરો",
      ifscCodeToastError: "કૃપા કરીને IFSC કોડ દાખલ કરો",
      panNoToastError: "કૃપા કરીને પાન નંબર દાખલ કરો",
      ifscCodeIncorrectToastError:
        "કૃપા કરીને સાચા ફોર્મેટમાં IFSC કોડ દાખલ કરો",
      panNoToastIncorrectError: "કૃપા કરીને સાચા ફોર્મેટમાં પાન નંબર દાખલ કરો",
      memberNameSearchPlaceholder: "સભ્યના નામ માટે શોધો...",
      activeSearchPlaceholder: "સક્રિય સ્થિતિ માટે શોધો...",
      memberMobileSearchPlaceholder: "સભ્યના મોબાઇલ નંબર માટે શોધો...",
      memberWardSearchPlaceholder: "સભ્યના વોર્ડ માટે શોધો...",
      memberPoliticalPartySearchPlaceholder: "સભ્યના રાજકીય પક્ષ માટે શોધો...",
    },
    memberDisciplinary: {
      memberDisciplinaryDetails: "સભ્યની શાખાકીય બાબતો",
      addDisciplinaryDetails: "સભ્યની શાખાકીય બાબતો ઉમેરો",
      memberDisciplinaryList: "સભ્યની શાખાકીય બાબતોની યાદી",
      editDisciplinaryDetails: "સભ્યની શાખાકીય બાબતો સુધારો",
      electedMember: "ચૂંટાયેલ સભ્યો",
      committee: "સમિતિ",
      designation: "જ​વાબદારી",
      terms: "મુદત",
      electedMemberPlaceholder: "ચૂંટાયેલ સભ્ય પસંદ કરો",
      committeePlaceholder: "સમિતિ પસંદ કરો",
      designationPlaceholder: "જ​વાબદારી પસંદ કરો",
      fromDate: "મુદતની શરૂઆતની તારીખ",
      toDate: "મુદતની અંતની તારીખ",
      activeDocument: "સક્રિય દસ્તાવેજ",
      inActiveDocument: "નિષ્ક્રિય દસ્તાવેજ",

      incumbencyDetails: "સત્તાની વિગતો",
      incumbencyDetailsPlaceholder: "સત્તાની વિગતો પસંદ કરો",
      incumbencyDetailsToastError: "કૃપા કરીને સત્તાની વિગતો પસંદ કરો",
      memberToastError: "કૃપા કરીને ચૂંટાયેલ સભ્ય પસંદ કરો",
      committeeToastError: "કૃપા કરીને સમિતિ પસંદ કરો",
      designationToastError: "કૃપા કરીને જ​વાબદારી પસંદ કરો",
      fromDateToastError: "કૃપા કરીને મુદતની શરૂઆતની તારીખ કરો",
      toDateToastError: "કૃપા કરીને મુદતની અંતની તારીખ પસંદ કરો",
      activeDocumentToastError: "કૃપા કરીને સક્રિય દસ્તાવેજ અપલોડ કરો",
      inActiveDocumentToastError: "કૃપા કરીને નિષ્ક્રિય દસ્તાવેજ અપલોડ કરો",
    },
    proposalType: {
      proposalType: "પ્રસ્તાવનો પ્રકાર",
      addProposalType: "પ્રસ્તાવનો પ્રકાર દાખલ કરો",
      editProposalType: "પ્રસ્તાવનો પ્રકાર સુધારો કરો",
      proposalTypeList: "પ્રસ્તાવનો પ્રકારનું યાદી",
      proposalTypeName: "પ્રસ્તાવનો પ્રકાર નામ",
      proposalTypePlaceholder: "પ્રસ્તાવનો પ્રકાર દાખલ કરો",
      proposalTypeToastError: "કૃપા કરીને પ્રસ્તાવનો પ્રકાર દાખલ કરો",
      proposalTypeSearchPlaceholder: "પ્રસ્તાવનો પ્રકાર માટે શોધો...",
      minproposalTypeToastError:
        "પ્રસ્તાવનો પ્રકાર માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    proposalFor: {
      proposalFor: "દરખાસ્ત સંદર્ભે",
      addProposalFor: "દરખાસ્ત સંદર્ભે દાખલ કરો",
      editProposalFor: "દરખાસ્ત સંદર્ભે સુધારો કરો",
      proposalForList: "દરખાસ્ત સંદર્ભેનું યાદી",
      proposalForName: "દરખાસ્ત સંદર્ભે નામ",
      proposalForPlaceholder: "દરખાસ્ત સંદર્ભે દાખલ કરો",
      proposalForToastError: "કૃપા કરીને દરખાસ્ત સંદર્ભે દાખલ કરો",
      proposalForSearchPlaceholder: "દરખાસ્ત સંદર્ભે માટે શોધો...",
      minproposalForToastError:
        "દરખાસ્ત સંદર્ભે માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    status: {
      status: "સ્ટેટ્સ",
      addStatus: "સ્ટેટ્સ દાખલ કરો",
      editStatus: "સ્ટેટ્સ સુધારો",
      statusList: "સ્ટેટ્સની યાદી",
      statusName: "સ્ટેટ્સનું નામ",
      statusPlaceholder: "સ્ટેટ્સનું નામ દાખલ કરો",
      statusToastError: "કૃપા કરીને સ્ટેટ્સનું નામ દાખલ કરો",
      statusSearchPlaceholder: "સ્ટેટ્સ માટે શોધો...",
      minstatusToastError: "સ્ટેટ્સ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    year: {
      year: "વર્ષ",
      addYear: "વર્ષ દાખલ કરો",
      editYear: "વર્ષ સુધારો",
      yearList: "વર્ષની યાદી",
      yearName: "વર્ષ",
      yearPlaceholder: "વર્ષ દાખલ કરો",
      yearToastError: "કૃપા કરીને વર્ષ દાખલ કરો",
      yearSearchPlaceholder: "વર્ષ માટે શોધો...",
      minyearToastError: "વર્ષ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    proposal: {
      proposal: "દરખાસ્ત ",
      addProposal: "દરખાસ્ત દાખલ કરો",
      editProposal: "દરખાસ્ત સુધારો કરો",
      proposalList: "દરખાસ્તનું યાદી",
      proposalNo: "દરખાસ્તનું નંબર",
      sankalanNo: "સંકલન નંબર",
      mukSankalanNo: "મુ.ક. સંકલન નંબર",
      incomingDate: "આવતું તારીખ",
      proposalDate: "દરખાસ્ત તારીખ",
      inwardDate: "ઇનવર્ડ તારીખ",
      inwardTime: "ઇનવર્ડ સમય",
      title: "શીર્ષક",
      committee: "સમિતિ",
      department: "વિભાગ",
      subject: "વિષય",
      keywords: "કીવર્ડ્સ",
      keywordsToastError: "કૃપા કરીને કીવર્ડ્સ દાખલ કરો",
      committeeInwardNo: "વિભાગ ઇનવર્ડ નંબર",
      registerInwardNo: "નોંધણી ઇનવર્ડ નંબર",
      proposalType: "પ્રસ્તાવનો પ્રકાર",
      proposalFor: "દરખાસ્ત સંદર્ભે",
      proposalForCommittee: "દરખાસ્ત સંદર્ભે ( સમિતિ )",
      proposalStatus: "દરખાસ્તનું સ્ટેટ્સ",
      uploadDocument: "દસ્તાવેજ અપલોડ કરો",
      sankalanNoPlaceholder: "સંકલન નંબર દાખલ કરો",
      mukSankalanNoPlaceholder: "મુ.ક. સંકલન નંબર દાખલ કરો",
      incomingDatePlaceholder: "આવતું તારીખ દાખલ કરો",
      titlePlaceholder: "શીર્ષક દાખલ કરો",
      committeePlaceholder: "સમિતિ પસંદ કરો",
      departmentPlaceholder: "વિભાગ પસંદ કરો",
      subjectPlaceholder: "વિષય દાખલ કરો",
      committeeInwardNoPlaceholder: "વિભાગ ઇનવર્ડ નંબર દાખલ કરો",
      registerInwardNoPlaceholder: "નોંધણી ઇનવર્ડ નંબર દાખલ કરો",
      proposalTypePlaceholder: "પ્રસ્તાવનો પ્રકાર પસંદ કરો",
      proposalForPlaceholder: "દરખાસ્ત સંદર્ભે પસંદ કરો",
      proposalForCommitteePlaceholder: "દરખાસ્ત સંદર્ભે ( સમિતિ ) પસંદ કરો",
      proposalStatusPlaceholder: "દરખાસ્તનું સ્ટેટ્સ પસંદ કરો",
      sankalanNoToastError: "કૃપા કરીને સંકલન નંબર દાખલ કરો",
      mukSankalanNoToastError: "કૃપા કરીને મુ.ક. સંકલન નંબર દાખલ કરો",
      incomingDateToastError: "કૃપા કરીને દરખાસ્તની તારીખ દાખલ કરો",
      titleToastError: "કૃપા કરીને શીર્ષક દાખલ કરો",
      committeeToastError: "કૃપા કરીને સમિતિ પસંદ કરો",
      departmentToastError: "કૃપા કરીને વિભાગ પસંદ કરો",
      subjectToastError: "કૃપા કરીને વિષય દાખલ કરો",
      uploadDocumentToastError: "કૃપા કરીને દસ્તાવેજ અપલોડ કરો",
      committeeInwardNoToastError: "કૃપા કરીને વિભાગ ઇનવર્ડ નંબર દાખલ કરો",
      registerInwardNoToastError: "કૃપા કરીને નોંધણી ઇનવર્ડ નંબર દાખલ કરો",
      proposalTypeToastError: "કૃપા કરીને પ્રસ્તાવનો પ્રકાર પસંદ કરો",
      proposalForToastError: "કૃપા કરીને દરખાસ્ત સંદર્ભે પસંદ કરો",
      proposalStatusToastError: "કૃપા કરીને દરખાસ્તનું સ્ટેટ્સ પસંદ કરો",
      image: "ઇમાગે",
      video: "વિડિયો",
      pdf: "પીડીએફ",
      sankalanNoSearchPlaceholder: "સંકલન નંબર માટે શોધો...",
      inwardNoSearchPlaceholder: "નોંધણી ઇનવર્ડ નંબર માટે શોધો...",
      fromDateSearchPlaceholder: "તારીખ થી",
      toDateSearchPlaceholder: "આજ સુધી",
      registerinwardTimePlaceholder: "કૃપા કરીને ઇનવર્ડ સમય પસંદ કરો",
    },
    script: {
      script: "સંક્ષિપ્ત વર્ણન",
      scriptNo: "સંક્ષિપ્ત વર્ણનનો નંબર​​",
      scriptlist: "સંક્ષિપ્ત વર્ણન ની યાદી​",
      addScript: "સંક્ષિપ્ત વર્ણન દાખલ કરો​",
      statusPlaceholder: "સ્થિતિ પસંદ કરો",

      editScript: "સંક્ષિપ્ત વર્ણન સુધારો કરો",
      viewScript: "સ્ક્રિપ્ટ જુઓ",
      proposalNo: "દરખાસ્ત નંબર ",
      proposalNoPlaceholder: "દરખાસ્ત નંબર દાખલ કરો",
      proposalNoToast: "કૃપા કરીને દરખાસ્ત નંબર દાખલ કરો",
      date: "તારીખ",
      datePlaceholder: "તારીખ દાખલ કરો",
      dateToast: "કૃપા કરીને તારીખ દાખલ કરો",
      regInvertNo: "નોંધણી ઇનવર્ડ નંબર",
      regInwartNoPlaceholder: "નોંધણી ઇનવર્ડ નંબર દાખલ કરો",
      regInwartNoToast: "કૃપા કરીને નોંધણી ઇનવર્ડ નંબર દાખલ કરો",
      ejardar: "ઈજારદાર​",
      ejardarPlaceholder: "ઈજારદારનું નામ દાખલ કરો​",
      ejardarToast: "કૃપા કરીને ઈજારદારનું નામ દાખલ કરો",
      scriptFieled: "વર્ણન",
      scriptFieledPlaceholder: "વર્ણન દાખલ કરો​",
      scriptFieledToast: "કૃપા કરીને વર્ણન દાખલ કરો",
      remarks: "વિશેષ નોંધ",
      remarksPlaceholder: "વિશેષ નોંધ દાખલ કરો​",
      amount: "રકમ",
      amountPlaceholder: "રકમ દાખલ કરો",
      amountToast: "કૃપા કરીને રકમ દાખલ કરો",
    },
    agendaStatus: {
      agendaStatus: "એજન્ડા સ્ટેટ્સ",
      addAgendaStatus: "એજન્ડા સ્ટેટ્સ દાખલ કરો",
      editAgendaStatus: "એજન્ડા સ્ટેટ્સ સુધારો",
      agendaStatusList: "એજન્ડા સ્ટેટ્સની યાદી",
      agendaStatusName: "એજન્ડા સ્ટેટ્સનું નામ",
      agendaStatusPlaceholder: "એજન્ડા સ્ટેટ્સનું નામ દાખલ કરો",
      agendaStatusToastError: "કૃપા કરીને એજન્ડા સ્ટેટ્સનું નામ દાખલ કરો",
      agendaStatusSearchPlaceholder: "એજન્ડા સ્ટેટ્સ માટે શોધો...",
      minagendastatusToastError:
        "એજન્ડા સ્ટેટ્સ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    agenda: {
      agenda: "એજન્ડા",
      addAgenda: "એજન્ડા દાખલ કરો",
      editAgenda: "એજન્ડા સુધારો",
      subjectModal: "વિષયની વિગતો",
      subject: "વિષય",
      agendaList: "એજન્ડાની યાદી",
      agendaName: "એજન્ડાનું નામ",
      agendaDate: "એજન્ડાની તારીખ",
      agendaCreatedDate: "એજન્ડા તારીખ બનાવો",
      mettingDate: "મીટિંગની તારીખ",
      time: "સમય",
      proposalFor: "દરખાસ્ત સંદર્ભે",
      agendaDatePlaceholder: "એજન્ડાની તારીખ પસંદ કરો",
      mettingDatePlaceholder: "મીટિંગની તારીખ પસંદ કરો",
      timePlaceholder: "સમય પસંદ કરો",
      proposalForPlaceholder: "દરખાસ્ત સંદર્ભે પસંદ કરો",
      agendaDateToastError: "કૃપા કરીને એજન્ડાની તારીખ પસંદ કરો",
      mettingDateToastError: "કૃપા કરીને મીટિંગની તારીખ પસંદ કરો",
      timeToastError: "કૃપા કરીને સમય પસંદ કરો",
      proposalForToastError: "કૃપા કરીને દરખાસ્ત સંદર્ભે પસંદ કરો",
      agendaPlaceholder: "એજન્ડાનું નામ દાખલ કરો",
      agendaToastError: "કૃપા કરીને એજન્ડાનું નામ દાખલ કરો",
      shortScript: "ટૂંકી સ્ક્રિપ્ટ",
      srNo: "ક્રમાંક",
      committee: "સમિતિ",
      script: "સ્ક્રિપ્ટpt",
      status: "સ્ટેટ્સ",
      remarks: "શેરો",
      addRemarks: "શેરો ઉમેરો",
      remarksToastError: "કૃપા કરીને શેરો દાખલ કરો",

      date: "તારીખ",
      addShortScript: "ટૂંકી સ્ક્રિપ્ટ ઉમેરો",
      agendaNo: "એજન્ડા નંબર",
      agendaTitle: "એજન્ડા શીર્ષક",
      day: "દિવસ",
      purvani: "પૂર્વવાણી",
      addPurvani: "પૂર્વવાણી ઉમેરો",
      purvaniAgendaToast: "કૃપા કરીને એક સ્ક્રિપ્ટ પસંદ કરો",
      approvalMsg: "શું તમે ખરેખર આ રેકોર્ડ ઉમેરવા માંગો છો?",
      sendForApproval: "મંજૂરી માટે મોકલો",
      fromPersonName: "વ્યક્તિના નામનો પત્ર",
      letterHead: "લેટરહેડ પેપર",
      plainPaper: "સાદા પેપર",
      postName: "પોસ્ટનું નામ",
    },
    languageType: {
      languageTypeList: "ભાષાના પ્રકારોની સૂચિ",
      addLanguageType: "ભાષાનો પ્રકાર​ ઉમેરો",
      editLanguageType: "ભાષાનો પ્રકાર સુધારો",
      languageType: "ભાષાનાં પ્રકારો",
      languageName: "ભાષાનું નામ",
      languagePlaceholder: "ભાષાનું નામ દાખલ કરો",
      languageToastError: "કૃપા કરીને ભાષાનું નામ દાખલ કરો",
      languageCode: "ભાષાનો કોડ",
      languageCodePlaceholder: "ભાષાનો કોડ દાખલ કરો",
      languageCodeToastError: "કૃપા કરીને ભાષાનો કોડ દાખલ કરો",
      languageTypeSearchPlaceholder: "ભાષાનાં પ્રકારો માટે શોધો...",
      minlanguageTypeToastError:
        "ભાષાનો પ્રકાર માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
      minlanguageCodeToastError:
        "ભાષાનો કોડ માટે ઓછામાં ઓછા 2 અક્ષરો આવશ્યક છે",
    },
    letterType: {
      letterTypeList: "પત્રનાં પ્રકારોની સૂચિ",
      addLetterType: "પત્રનો પ્રકાર​ ઉમેરો",
      editLetterType: "પત્રનો પ્રકાર સુધારો",
      letterType: "પત્રનાં પ્રકારો",
      letterName: "પત્રનું નામ",
      letterPlaceholder: "પત્રનું નામ દાખલ કરો",
      letterToastError: "કૃપા કરીને પત્રનું નામ દાખલ કરો",
      letterTypeSearchPlaceholder: "પત્રનાં પ્રકારો માટે શોધો...",
      minletterTypeToastError: "પત્રનું નામ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
      letterForToastError: "કૃપા કરીને પત્ર સંદર્ભે પસંદ કરો",
      letterForPlaceHolder: "પત્ર સંદર્ભે પસંદ કરો",
      letterTypePlaceHolder: "પત્રનો પ્રકાર પસંદ કરો ",
    },
    letterField: {
      letterFieldList: "પત્રની ફિલ્ડોની સુચી",
      addLetterField: "પત્રની ફિલ્ડ ઉમેરો",
      editLetterField: "પત્રની ફિલ્ડ સુધારો",
      letterField: "પત્રની ફિલ્ડ",
      fieldName: "ફિલ્ડનું નામ",
      fieldType: "ફિલ્ડનો પ્રકાર",
      fieldToken: "ફિલ્ડનો સંબંધ",
      fieldPlaceholder: "ફિલ્ડનું નામ દાખલ કરો",
      fieldToastError: "કૃપા કરીને ફિલ્ડનું નામ દાખલ કરો",
      letterToastError: "કૃપા કરીને પત્ર પસંદ કરો",
      dataTypeToastError: "કૃપા કરીને ફિલ્ડનો પ્રકાર પસંદ કરો",
      fieldTokenToastError: "કૃપા કરીને ફિલ્ડનો સંબંધ દાખલ કરો",
      letterType: "પત્રનો પ્રકાર",
      letterTypePlaceHolder: "પત્રનો પ્રકાર પસંદ કરો",
      fieldDataTypePlaceholder: "ફિલ્ડનો પ્રકાર પસંદ કરો",
      fieldTokenPlaceholder: "ફિલ્ડનો સંબંધ દાખલ કરો",
      letterFieldSearchPlaceholder: "પત્રની ફિલ્ડ માટે શોધો...",
      letterTypeSearchPlaceholder: "પત્રનાં પ્રકારો માટે શોધો...",
      letterTokenPlaceholder: "પત્રની ફિલ્ડ પસંદ કરો",
    },
    letterContent: {
      letterContentList: "પત્રની વિગતોની સુચી",
      addLetterContent: "પત્રની વિગતો ઉમેરો",
      editLetterContent: "પત્રની વિગતો સુધારો",
      letterContent: "પત્રની વિગતો",
      content: "વિગત",
      contentPlaceholder: "વિગત દાખલ કરો",
      contentToastError: "કૃપા કરીને વિગત દાખલ કરો",
      languageType: "ભાષાનાં પ્રકારો",
      languagePlaceholder: "ભાષાનાં પ્રકારો પસંદ કરો",
      languageToastError: "કૃપા કરીને ભાષાનો પ્રકારો પસંદ કરો",
      letterType: "પત્રનો પ્રકાર",
      letterTypePlaceholder: " પત્રનો પ્રકાર પસંદ કરો",
      letterTypeToastError: "કૃપા કરીને પત્રનો પ્રકાર પસંદ કરો",
      letterTypeSearchPlaceholder: "પત્રનો પ્રકાર માટે શોધો...",
      minletterContentToastError: "વિગત માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    changePassword: {
      changePassword: "પાસવર્ડ બદલો",
      oldPassword: "જુનો પાસવર્ડ",
      newPassword: "નવો પાસવર્ડ",
      confirmPassword: "કન્ફર્મ પાસવર્ડ",
      oldPasswordPlaceholder: "જુનો પાસવર્ડ દાખલ કરો",
      newPasswordPlaceholder: "નવો પાસવર્ડ દાખલ કરો",
      confirmPasswordPlaceholder: "કન્ફર્મ પાસવર્ડ દાખલ કરો",
      passwordRegexToastError: "પાસવર્ડ યોગ્ય ફોર્મેટમાં નથી",

      oldPasswordToastError: "કૃપા કરીને જુનો પાસવર્ડ દાખલ કરો",
      oldPasswordToastError2: "જૂના પાસવર્ડની લઘુત્તમ લંબાઈ 6 હોવી જોઈએ",
      newPasswordToastError: "કૃપા કરીને નવો પાસવર્ડ દાખલ કરો",
      newPasswordToastError2: "નવા પાસવર્ડની લઘુત્તમ લંબાઈ 6 હોવી જોઈએ",
      confirmPasswordToastError: "કૃપા કરીને કન્ફર્મ પાસવર્ડ દાખલ કરો",
      confirmPasswordToastError2: "કન્ફર્મ પાસવર્ડની લઘુત્તમ લંબાઈ 6 હોવી જોઈએ",
      passwordNotMatchToastError:
        "નવો પાસવર્ડ અને કન્ફર્મ પાસવર્ડ બરાબર નથી. ફરી દાખલ કરી જુઓ !",
    },
    department: {
      department: "વિભાગો",
      addDepartment: "વિભાગ દાખલ કરો",
      editDepartment: "વિભાગ સુધારો",
      departmentList: "વિભાગોની યાદી",
      departmentName: "વિભાગનું નામ",
      departmentPlaceholder: "વિભાગનું નામ દાખલ કરો",
      departmentToastError: "કૃપા કરીને વિભાગનું નામ દાખલ કરો",
      departmentSearchPlaceholder: "વિભાગ માટે શોધો...",
      mindepartmentToastError: "વિભાગ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    letterFor: {
      letterFor: "પત્ર સંદર્ભે",
      addletterFor: "પત્ર સંદર્ભે દાખલ કરો",
      editletterFor: "પત્ર સંદર્ભે સુધારો કરો",
      letterForList: "પત્ર સંદર્ભેનું યાદી",
      letterForName: "પત્ર સંદર્ભે નામ",
      letterForPlaceholder: "પત્ર સંદર્ભે દાખલ કરો",
      letterForToastError: "કૃપા કરીને પત્ર સંદર્ભે દાખલ કરો",
      letterForSearchPlaceholder: "પત્ર સંદર્ભે માટે શોધો...",
      minletterForToastError: "પત્ર સંદર્ભે માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    issueLetter: {
      issueLetter: "પત્ર નોંધણી",
      addLetterHistory: "પત્ર નોંધણી દાખલ કરો",
      letterHistory: "પત્ર નોંધણી",
      letterHistoryList: "પત્ર નોંધણી યાદી",

      createdAt: "નિર્માણ તારીખ",
      parameters: "પરિમાણો",
      date: "તારીખ પસંદ કરો",
    },
    pendingAgendaApproval: {
      pendingAgendaApproval: "બાકી એજન્ડાની મંજૂરી",
      pendingAgendaApprovalList: "બાકી એજન્ડાની મંજૂરી યાદી",
      viewAgenda: "કાર્યસૂચિ જુઓ",
      approveAgenda: "મંજૂર",
      rejectAgenda: "અસ્વીકાર કરો",
      approvalMsg: "શું તમે ખરેખર આ રેકોર્ડને મંજૂર કરવા માંગો છો ?",
      rejectMsg: "શું તમે ખરેખર આ રેકોર્ડને નકારવા માંગો છો ?",
    },
    resolution: {
      resolution: "ઠરાવ",
      addresolution: "ઠરાવ ઉમેરો",
      resolutionList: "ઠરાવ યાદી",
      postponed: "મુલતવી",
      adhyaksh: "અધ્યક્ષ",
      nameProposal: "દરખાસ્ત કરનારનું નામ",
      nameApproval: "અનુમોદન આપનારનું નામ",
      supporter: "તરફેણમાં",
      opposition: "વિરુધ્ધમાં",
      adhyakshMemberToastError: "કૃપા કરીને અધ્યક્ષ પસંદ કરો",
      meaning: "મતલબ​",
      previousResolution: "પાછલો ઠરાવ",
      nextResolution: "આગળનો ઠરાવ",
      remarks: "શેરો",
      proposalOrCorrectionDetails: "દરખાસ્ત / સુઘારો",
      confrimMsg: "શું તમે ખરેખર પોસ્પોન્ડ સ્ક્રિપ્ટ કરવા માંગો છો",
      contentTextSize: "સામગ્રી લખાણ કદ",
      headerTextSize: "હેડર ટેક્સ્ટનું કદ",
      notes: "નોંધો",
      showNameInPdf:
        "શું તમે પીડીએફમાં સમર્થક અને વિપક્ષનું નામ બતાવવા માંગો છો ?",
      addCorrectionProposal: "સુધારણા દરખાસ્ત ઉમેરો",
      correctionProposal: "સુધારણા દરખાસ્ત",
      deleteProposal: "દરખાસ્ત કાઢી નાખો",
      correctionProposalToastError: "કૃપા કરીને સુધારણા દરખાસ્ત દાખલ કરો",
    },
    proceeding: {
      proceeding: "પ્રક્રિયા",
      addProceeding: "પ્રક્રિયા ઉમેરો",
      proceedingList: "પ્રક્રિયા યાદી",
      aboutMetting: "મીટીંગ વિશે",
      administrativeDetails: "વહીવટી વિગતો",
      agendaToastError: "કૃપા કરીને એજન્ડા પસંદ કરો",
      membersToastError: "કૃપા કરીને સભ્ય પસંદ કરો",
      aboutMettingToastError: "કૃપા કરીને મીટિંગ વિશે દાખલ કરો",
      administrativeDetailsToastError: "કૃપા કરીને વહીવટી વિગતો દાખલ કરો",
      scriptNo: "સ્ક્રિપ્ટ નંબર",
      scriptToastError: "કૃપા કરીને સ્ક્રિપ્ટ પસંદ કરો",
    },
    stationeryMaterial: {
      stationeryMaterial: "સ્ટેશનરી સામગ્રી",
      addStationeryMaterial: "સ્ટેશનરી સામગ્રી ઉમેરો",
      editStationeryMaterial: "સ્ટેશનરી સામગ્રી સુધારો",
      stationeryMaterialList: "સ્ટેશનરી સામગ્રીની યાદી",
      stationeryMaterialName: "સ્ટેશનરી સામગ્રીનું નામ",
      stationeryMaterialPlaceholder: "સ્ટેશનરી સામગ્રીનું નામ દાખલ કરો",
      stationeryMaterialToastError:
        "કૃપા કરીને સ્ટેશનરી સામગ્રીનું નામ દાખલ કરો",
      stationeryMaterialSearchPlaceholder: "સ્ટેશનરી સામગ્રી માટે શોધો...",
      minstationeryMaterialToastError:
        "સ્ટેશનરી સામગ્રી માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
      materialShortName: "સામગ્રીનું ટૂંકું નામ",
      materialShortNamePlaceholder: "સામગ્રીનું ટૂંકું નામ દાખલ કરો",
      materialShortNameToastError: "કૃપા કરીને સામગ્રીનું ટૂંકું નામ દાખલ કરો",
      minmaterialShortNameToastError:
        "સામગ્રીના ટૂંકા નામમાં ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    stationeryWork: {
      stationeryWork: "સ્ટેશનરી કામ",
      addStationeryWork: "સ્ટેશનરી કામ ઉમેરો",
      editStationeryWork: "સ્ટેશનરી કામ સુધારો",
      stationeryWorkList: "સ્ટેશનરી કામની યાદી",
      stationeryWorkName: "સ્ટેશનરી કામનું નામ",
      stationeryWorkPlaceholder: "સ્ટેશનરી કામનું નામ દાખલ કરો",
      stationeryWorkToastError: "કૃપા કરીને સ્ટેશનરી કામનું નામ દાખલ કરો",
      stationeryWorkSearchPlaceholder: "સ્ટેશનરી કામ માટે શોધો...",
      minstationeryWorkToastError:
        "સ્ટેશનરી કામ માટે ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
      date: "તારીખ ",
      date2: "તારીખ ",
      datePlaceholder: "તારીખ પસંદ કરો",
      date2Placeholder: "તારીખ પસંદ કરો",
      memberName: "સભ્યનું નામ",
      materialName: "સામગ્રીનું નામ",
      materialLanguage: "સામગ્રીની ભાષા",
      qty: "જથ્થો",
      issueMaterial: "મુદ્દાની સામગ્રીની વિગતો",
      supplyQty: "જથ્થો/સંખ્યા",
      price: "કિંમત",
      remarks: "શેરો",
      memberPlaceholder: "સભ્યનું નામ પસંદ કરો",
      materialLanguagePlaceholder: "સામગ્રીની ભાષા",
      dateToastError: "કૃપા કરીને તારીખ પસંદ કરો",
      memberNameToastError: "કૃપા કરીને સભ્યનું નામ પસંદ કરો",
      materialLanguageToastError: "કૃપા કરીને સામગ્રીની ભાષા પસંદ કરો",
      materialNameToastError: "કૃપા કરીને સામગ્રીનું નામ પસંદ કરો",
      qtyToastError: "કૃપા કરીને સંખ્યા દાખલ કરો",
      supplyQtyToastError: "કૃપા કરીને સપ્લાય જથ્થો દાખલ કરો",
      priceToastError: "કૃપા કરીને કિંમત દાખલ કરો",
      totalPrice: "કુલ કિંમત",
      pageNo: "પાન નંબર",
      indexNo: "અનુકમ નંબર",
      pageNoToastError: "કૃપા કરીને પાન નંબર દાખલ કરો",
      indexNoToastError: "કૃપા કરીને અનુકમ નંબર દાખલ કરો",
    },
    salaryDetail: {
      salaryDetail: "માનદ વેતનની વિગતો ",
      addSalaryDetail: "માનદ વેતનની વિગતો ઉમેરો",
      editSalaryDetail: "માનદ વેતનની વિગતો સુધારો",
      salaryDetailList: "માનદ વેતનની વિગતોની યાદી",
      houseBuildingLetterNo: "ગૃહ નિર્માણ વિભાગના પત્ર કમાંક",
      houseBuildingDate: "ગૃહ નિર્માણ વિભાગના પત્ર કમાંક તારીખ",
      assemblyResolutionNo: "સામાન્ય સભા ઠરાવ નંબર",
      assemblyResolutionDate: "સામાન્ય સભા ઠરાવ તારીખ",
      declarationDate: "જાહેરનામું તારીખ",
      totalSalary: "માનદ વેતન",
      telephoneAllowance: "ટેલીફોન એલાઉન્સ",
      stationeryAllowance: "સ્ટેશનરી એલાઉન્સ",
      meetingAllowance: "સભા એલાઉન્સ",
      maximumMeetingAllowance: "મહત્તમ સભા એલાઉન્સ",
      houseBuildingLetterNoToastError:
        "કૃપા કરીને ગૃહ નિર્માણ વિભાગના પત્ર કમાંક દાખલ કરો",
      houseBuildingDateToastError:
        "કૃપા કરીને ગૃહ નિર્માણ વિભાગના પત્ર કમાંક તારીખ દાખલ કરો",
      assemblyResolutionNoToastError:
        "કૃપા કરીને સામાન્ય સભા ઠરાવ નંબર દાખલ કરો",
      assemblyResolutionDateToastError:
        "કૃપા કરીને સામાન્ય સભા ઠરાવ તારીખ દાખલ કરો",
      declarationDateToastError: "કૃપા કરીને જાહેરનામું તારીખ દાખલ કરો",
      totalSalaryToastError: "કૃપા કરીને માનદ વેતન દાખલ કરો",
      telephoneAllowanceToastError: "કૃપા કરીને ટેલીફોન એલાઉન્સ દાખલ કરો",
      stationeryAllowanceToastError: "કૃપા કરીને સ્ટેશનરી એલાઉન્સ દાખલ કરો",
      meetingAllowanceToastError: "કૃપા કરીને સભા એલાઉન્સ દાખલ કરો",
      maximumMeetingAllowanceToastError:
        "કૃપા કરીને મહત્તમ સભા એલાઉન્સ દાખલ કરો",
    },
    issueSalary: {
      issueSalary: "ઇશ્યૂ માનદ વેતન",
      addIssueSalary: "ઇશ્યૂ માનદ વેતન ઉમેરો",
      memberShipPageNo: "અંઘજપત્રક પાન નંબર",
      totalDays: "કુલ દિવસો",
      totalPrice: "કુલ કિંમત",
      fromDateToastError: "કૃપા કરીને તારીખથી પસંદ કરો",
      toDateToastError: "કૃપા કરીને તારીખથી પસંદ કરો",
      memberShipPageNoToastError: "કૃપા કરીને અંઘજપત્રક પાન નંબર દાખલ કરો",
    },
    vendorDetail: {
      vendorDetail: "વિક્રેતા વિગતો",
      addVendorDetail: "વિક્રેતા વિગતો ઉમેરો",
      editVendorDetail: "વિક્રેતા વિગતો સુધારો",
      vendorDetailList: "વિક્રેતા વિગતો યાદી",
      vendorName: "વિક્રેતાનું નામ",
      companyName: "કંપની નું નામ",
      address: "સરનામું",
      mobileNo: "મોબાઇલ નંબર",
      vendorNameSearchPlaceholder: "વિક્રેતાનું નામ શોધો",

      vendorNamePlaceholder: "વિક્રેતાનું નામ દાખલ કરો",
      companyNamePlaceholder: "કંપનીનું નામ દાખલ કરો",
      mobileNoPlaceholder: "મોબાઈલ નંબર દાખલ કરો",
      addressPlaceholder: "સરનામું દાખલ કરો",
      vendorNameToastError: "કૃપા કરીને વિક્રેતાનું નામ દાખલ કરો",
      companyNameToastError: "કૃપા કરીને કંપનીનું નામ દાખલ કરો",
      mobileNoToastError: "કૃપા કરીને મોબાઈલ નંબર દાખલ કરો",
      addressToastError: "કૃપા કરીને સરનામું દાખલ કરો",
      mobileNoLengthToastError: "કૃપા કરીને યોગ્ય મોબાઇલ નંબર દાખલ કરો",
      minLengthToastError: "ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    paperDetail: {
      paperDetail: "પેપરની વિગતો",
      addPaperDetail: "પેપરની વિગતો ઉમેરો",
      editPaperDetail: "પેપરની વિગતો સુધારો",
      paperDetailList: "પેપરની વિગતો યાદી",
      paperName: "પેપરનું નામ",
      paperDetailSerachPlaceholder: "પેપરનું નામ શોધો",
      price: "કિંમત",
      paperNamePlaceholder: " પેપરનું નામ દાખલ કરો",
      pricePlaceholder: " કિંમત દાખલ કરો",
      paperNameToastError: "કૃપા કરીને પેપરનું નામ દાખલ કરો",
      priceToastError: "કૃપા કરીને કિંમત દાખલ કરો",
      minLengthToastError: "ઓછામાં ઓછા 3 અક્ષરો આવશ્યક છે",
    },
    paperWork: {
      paperWork: "પેપરની કામ",
      addPaperWork: "પેપરની કામ ઉમેરો",
      editPaperWork: "પેપરની કામ સુધારો",
      paperWorkList: "પેપરની કામની યાદી",
      month: "મહિનો",
      advanceAmount: "એડવાન્સ રકમ",
      vendorPlaceholder: "વિક્રેતા વિગતો પસંદ કરો",
      monthPlaceholder: "મહિનો પસંદ કરો",
      advanceAmountPlaceholder: "Enter a એડવાન્સ રકમ",
      vendorToastError: "કૃપા કરીને વિક્રેતા વિગતો દાખલ કરો",
      monthToastError: "કૃપા કરીને મહિનો દાખલ કરો",
      advanceAmountToastError: "કૃપા કરીને એડવાન્સ રકમ દાખલ કરો",
      paperName: "પેપરનું નામ",
      paperType: "પેપરનું પ્રકાર",
      paperNamePlaceholder: "પેપરનું નામ પસંદ કરો",
      paperTypePlaceholder: "પેપરનું પ્રકાર પસંદ કરો",
      paperNameToastError: "કૃપા કરીને પેપરનું નામ પસંદ કરો",
      paperTypeToastError: "કૃપા કરીને પેપરનું પ્રકાર પસંદ કરો",
      day: "દિવસ",
      price: "કિંમત",
      totalPrice: "કુલ કિંમત",
      qty: "નંગ",
      amount: "રકમ",
      dayToastError: "કૃપા કરીને દિવસ દાખલ કરો",
      priceToastError: "કૃપા કરીને કિંમત દાખલ કરો",
      totalPriceToastError: "કૃપા કરીને કુલ કિંમત દાખલ કરો",
      qtyToastError: "કૃપા કરીને નંગ દાખલ કરો",
      amountToastError: "કૃપા કરીને રકમ દાખલ કરો",
    },
    dashboard: {
      totalScript: "કુલ સ્ક્રિપ્ટ",
      scriptStatus: "સ્ક્રિપ્ટ સ્ટેટસ",
      upcomingMetting: "આગામી બેઠક",
      viewAll: "બધુજ જુઓ",
      proposalStatistics: "દરખાસ્તના આંકડા",
      totalProposal: "કુલ દરખાસ્ત",
      totalGeneratedScript: "કુલ જનરેટેડ સ્ક્રિપ્ટ",
      pendingGeneratedScript: "બાકી જનરેટેડ સ્ક્રિપ્ટ",
      issueLetterMsg:
        "ઇશ્યૂ લેટરનો હેતુ સંબંધિત પક્ષોને ઔપચારિક રીતે વાતચીત કરવાનો છે.",
      totalissuedLetter: "કુલ જારી પત્ર",
      todayCount: "આજરોજની ગણતરી",
    },
    report: {
      report: "રિપોર્ટ",
      reportType: "રિપોર્ટ પ્રકાર",
    },
    correctionProposal: {
      correctionProposalList: "સુધારણા દરખાસ્તની યાદી",
      addCorrectionProposal: "સુધારણા દરખાસ્ત ઉમેરો",
      editCorrectionProposal: "સુધારણા દરખાસ્ત સુધારો",
      correctionProposal: "સુધારણા દરખાસ્ત",
      correctionProposalSearchPlaceholder: "સુધારણા દરખાસ્ત માટે શોધો...",
      uploadData: "ડેટા અપલોડ કરો",
      scriptToastError: "કૃપા કરીને સ્ક્રિપ્ટ દાખલ કરો",
      budgetItemSerialNo: "બજેટ આઇટમ સીરીયલ નંબર",
      correctionProposalNo: "સુધારણા દરખાસ્ત નંબર",
      arrangeCorrectionProposal: "સુધારણા દરખાસ્ત ગોઠવો",
    },
  },
};
